
from django.db import models
from django.core.exceptions import ValidationError
from django.core import validators
from django.utils import timezone

class Notice(models.Model):
    title = models.CharField(max_length=255,)
    slug = models.SlugField(max_length=255, unique=True, blank=True, null=True)
    file = models.FileField(upload_to="notices/", blank=True, null=True, verbose_name="পিডিএফ ফাইল (ঐচ্ছিক)")
    expiry_date = models.DateField(blank=True, null=True, verbose_name="মেয়াদ শেষ হওয়ার তারিখ (ঐচ্ছিক)")
    created_at = models.DateTimeField(auto_now_add=True,)
    is_active = models.BooleanField(default=True, )
   
    class Meta:
        ordering = ['-created_at']

    def __str__(self):
        return self.title


class Teacher(models.Model):
                                                                        
    name = models.CharField(max_length=150, )
    designation = models.CharField(max_length=100, )
    department = models.CharField(max_length=100, blank=True, null=True)
    image = models.ImageField(upload_to="teachers/", blank=True, null=True, verbose_name="ছবি (পাসপোর্ট সাইজ)")
    email = models.EmailField(max_length=30, blank=True, null= True)
    mobile = models.CharField(max_length=20, blank=True, null=True)
    order = models.PositiveIntegerField(default=0, )

    class Meta:
        ordering = ['order', 'name']

    def __str__(self):
        return f"{self.name} - {self.designation}"
class Student(models.Model):
    name = models.CharField(max_length=150, )
    roll_number = models.CharField(max_length=10, unique=True)
    section = models.CharField(max_length=10, blank=True, null=True)
    date_of_birth = models.DateField(blank=True, null=True)
    gender = models.CharField(max_length=10, choices=[('male', 'Male'), ('female', 'Female')], blank=True, null=True)
    father_name = models.CharField(max_length=150, blank=True, null=True)
    mother_name = models.CharField(max_length=150, blank=True, null=True)
    phone = models.CharField(max_length=20, blank=True, null=True)
    image = models.ImageField(upload_to="students/", verbose_name="ছবি (পাসপোর্ট সাইজ)", blank=True, null=True)
    created_at = models.DateField(auto_now_add=True,)
    updated_at = models.DateField(auto_now=True,)

    class Meta:
        ordering = ['roll_number']

    def __str__(self):
        return f"{self.name} - {self.roll_number}"
class Administration(models.Model):
    name = models.CharField(max_length=150, )
    designation = models.CharField(max_length=100, )
    image = models.ImageField(upload_to="administration/", verbose_name="ছবি (পাসপোর্ট সাইজ)")

    def clean(self):
        if not self.pk and Administration.objects.count() >= 3:
            raise ValidationError("শুধুমাত্র ৩ জন Administration যোগ করা যাবে।")
    def __str__(self):
        return "Administration Message"
def current_year():
    return timezone.now().year


class Subject(models.Model):
    """Subject model for storing subject information."""
    name = models.CharField(max_length=150, unique=True)
    code = models.CharField(max_length=20, blank=True, null=True)
    full_marks = models.PositiveIntegerField(default=100)
    pass_marks = models.PositiveIntegerField(default=33)
    is_active = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['name']
        verbose_name = "Subject"
        verbose_name_plural = "Subjects"

    def __str__(self):
        return f"{self.name} ({self.code})" if self.code else self.name

    def clean(self):
        if self.full_marks < self.pass_marks:
            raise ValidationError("Pass marks cannot exceed full marks.")
        if self.full_marks <= 0:
            raise ValidationError("Full marks must be greater than 0.")


class Result(models.Model):
    """
    Result Summary Model.
    Stores one record per (student, class, passing_year).
    All calculated fields are auto-generated by signals.
    """
    CLASS_CHOICES = [
        ('class_6', 'Class 6'),
        ('class_7', 'Class 7'),
        ('class_8', 'Class 8'),
        ('class_9', 'Class 9'),
        ('class_10', 'Class 10'),
    ]

    RESULT_STATUS_CHOICES = [
        ('PASS', 'PASS'),
        ('FAIL', 'FAIL'),
    ]

    student = models.ForeignKey(
        Student,
        on_delete=models.CASCADE,
        related_name='results_summary',
    )
    roll_number = models.CharField(max_length=20)
    class_name = models.CharField(max_length=50, choices=CLASS_CHOICES)
    passing_year = models.PositiveIntegerField(default=current_year)

    # Automatically calculated fields
    total_subjects = models.PositiveIntegerField(default=0)
    total_marks = models.DecimalField(max_digits=6, decimal_places=2, default=0)
    average_gpa = models.DecimalField(max_digits=4, decimal_places=2, default=0)
    final_grade = models.CharField(max_length=2, blank=True, null=True)
    result_status = models.CharField(
        max_length=10,
        choices=RESULT_STATUS_CHOICES,
        default='PASS'
    )

    # Metadata
    published_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-passing_year', 'roll_number', 'class_name','total_marks', 'average_gpa']
        verbose_name = "Result Summary"
        verbose_name_plural = "Result Summaries"
        constraints = [
            models.UniqueConstraint(
                fields=['roll_number', 'class_name', 'passing_year'],
                name='unique_result_per_student_class_year'
            )
        ]

    def __str__(self):
        return f"{self.roll_number} - {self.class_name} ({self.passing_year})"


class ResultDetail(models.Model):
    """
    Result Details Model.
    Stores individual subject scores.
    Teachers only enter: roll_number, class_name, passing_year, subject, marks.
    Everything else is auto-calculated.
    """
    result = models.ForeignKey(
        Result,
        on_delete=models.CASCADE,
        related_name='detail_scores',
    )
    roll_number = models.CharField(max_length=20)
    class_name = models.CharField(max_length=50, choices=Result.CLASS_CHOICES)
    passing_year = models.PositiveIntegerField()
    subject = models.ForeignKey(Subject, on_delete=models.CASCADE)

    # Teacher enters this
    marks = models.DecimalField(
        max_digits=5,
        decimal_places=2,
        validators=[
            validators.MinValueValidator(0),
        ]
    )

    # Auto-calculated fields (read-only)
    gpa = models.DecimalField(max_digits=4, decimal_places=2, default=0)
    grade = models.CharField(max_length=2, default='F')

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['result', 'subject']
        verbose_name = "Result Detail"
        verbose_name_plural = "Result Details"
        constraints = [
            models.UniqueConstraint(
                fields=['result', 'subject'],
                name='unique_subject_per_result'
            )
        ]

    def __str__(self):
        return f"{self.roll_number} - {self.subject.name} - {self.marks}/{self.subject.full_marks}"

    def clean(self):
        if self.marks > self.subject.full_marks:
            raise ValidationError(
                f"Marks cannot exceed {self.subject.full_marks}."
            )
        if self.marks < 0:
            raise ValidationError("Marks cannot be negative.")


class Certificate(models.Model):
    certificate_number = models.CharField(max_length=50, unique=True)
    student_name = models.CharField(max_length=150)
    course_name = models.CharField(max_length=150)
    issue_date = models.DateField()
    status = models.CharField(max_length=50, default='Verified')
    remarks = models.TextField(blank=True, null=True)

    class Meta:
        ordering = ['-issue_date']

    def __str__(self):
        return self.certificate_number


class AttendanceRecord(models.Model):
    student_name = models.CharField(max_length=150)
    class_name = models.CharField(max_length=50)
    attendance_date = models.DateField()
    status = models.CharField(max_length=20, default='Present')
    remarks = models.TextField(blank=True, null=True)

    class Meta:
        ordering = ['-attendance_date', 'student_name']

    def __str__(self):
        return f"{self.student_name} - {self.attendance_date}"


class ExamSchedule(models.Model):
    title = models.CharField(max_length=200)
    class_name = models.CharField(max_length=50)
    exam_date = models.DateField()
    details = models.TextField(blank=True, null=True)
    created_at = models.DateField(auto_now_add=True)

    class Meta:
        ordering = ['exam_date', 'title']

    def __str__(self):
        return self.title


class Routine(models.Model):
    class_name = models.CharField(max_length=50)
    day = models.CharField(max_length=20)
    time_slot = models.CharField(max_length=50)
    subject = models.CharField(max_length=150)
    teacher_name = models.CharField(max_length=150, blank=True, null=True)
    created_at = models.DateField(auto_now_add=True)

    class Meta:
        ordering = ['day', 'time_slot', 'class_name']

    def __str__(self):
        return f"{self.class_name} - {self.day} - {self.subject}"


class GalleryImage(models.Model):
    caption = models.CharField(max_length=200,)
    image = models.ImageField(upload_to="gallery/")
    uploaded_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.caption




class ImportantLink(models.Model):
    title = models.CharField(max_length=150, )
    url = models.URLField(max_length=500, )
    order = models.PositiveIntegerField(default=0,)
    is_active = models.BooleanField(default=True, )

    class Meta:
        ordering = ['order', 'title']
        

    def __str__(self):
        return self.title

class ContactMessage(models.Model):
    name = models.CharField(max_length=150,)
    contact_info = models.CharField(max_length=150,)
    message = models.TextField()
    received_at = models.DateTimeField(auto_now_add=True,)

    class Meta:
        ordering = ['-received_at']

    def __str__(self):
        return f"{self.name} - {self.received_at.strftime('%d-%m-%Y')}"