# Generated by Django 6.0.7 on 2026-07-19 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sclapp', '0003_administration_result_student_delete_headteacher_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=150)),
                ('class_name', models.CharField(max_length=50)),
                ('attendance_date', models.DateField()),
                ('status', models.CharField(default='Present', max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-attendance_date', 'student_name'],
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_number', models.CharField(max_length=50, unique=True)),
                ('student_name', models.CharField(max_length=150)),
                ('course_name', models.CharField(max_length=150)),
                ('issue_date', models.DateField()),
                ('status', models.CharField(default='Verified', max_length=50)),
                ('remarks', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-issue_date'],
            },
        ),
        migrations.CreateModel(
            name='ExamSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('class_name', models.CharField(max_length=50)),
                ('exam_date', models.DateField()),
                ('details', models.TextField(blank=True, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ['exam_date', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Routine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=50)),
                ('day', models.CharField(max_length=20)),
                ('time_slot', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=150)),
                ('teacher_name', models.CharField(blank=True, max_length=150, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ['day', 'time_slot', 'class_name'],
            },
        ),
    ]
