# Generated by Django 6.0.7 on 2026-07-20 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sclapp', '0009_resultdetail_subject_alter_result_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultdetail',
            name='class_name',
            field=models.CharField(choices=[('class_6', 'Class 6'), ('class_7', 'Class 7'), ('class_8', 'Class 8'), ('class_9', 'Class 9'), ('class_10', 'Class 10')], max_length=50),
        ),
    ]
