# Generated by Django 6.0.7 on 2026-07-20 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sclapp', '0011_alter_result_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='teachers/', verbose_name='ছবি (পাসপোর্ট সাইজ)'),
        ),
    ]
