# Generated by Django 6.0.7 on 2026-07-20 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sclapp', '0013_alter_teacher_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
