# Generated by Django 6.0.7 on 2026-07-18 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sclapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='headteacher',
            name='message',
        ),
        migrations.AddField(
            model_name='headteacher',
            name='designation',
            field=models.CharField(default='N/A', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='headteacher',
            name='name',
            field=models.CharField(default='exit', max_length=150),
            preserve_default=False,
        ),
    ]
