# Generated by Django 6.0.7 on 2026-07-20 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sclapp', '0007_alter_result_class_name_alter_result_passing_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='class_name',
        ),
    ]
